name: App Deploy (S3 + CloudFront)
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**"
      - "!README.md"
  push:
    branches: [ "main" ]
    paths:
      - "**"
      - "!README.md"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-2
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CF_DIST_ID: ${{ vars.CF_DIST_ID }}
  GHA_APP_ROLE_ARN: ${{ vars.GHA_APP_ROLE_ARN }}

jobs:
  secret-scan:
    name: Secret Leak Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main

  codeql-analyze:
    needs: [secret-scan]
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [secret-scan, codeql-analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps & build
        run: |
          npm ci
          npm run build
      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.GHA_APP_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload assets (immutable)
        run: |
          aws s3 sync build/ s3://$S3_BUCKET             --cache-control "public,max-age=31536000,immutable"             --delete

      - name: Upload index.html (no-cache)
        run: |
          aws s3 cp build/index.html s3://$S3_BUCKET/index.html             --cache-control "no-cache"             --metadata-directive REPLACE             --content-type text/html

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation             --distribution-id "$CF_DIST_ID"             --paths "/index.html" "/"
